export const ACTION_NAME_METADATA = 'NEST_CRUD_ACTION_NAME_METADATA';
export const OVERRIDE_METHOD_METADATA = 'NEST_CRUD_OVERRIDE_METHOD_METADATA';
export const PARSED_BODY_METADATA = 'NEST_CRUD_PARSED_BODY_METADATA';
export const PARSED_CRUD_REQUEST_KEY = 'NEST_CRUD_PARSED_CRUD_REQUEST_KEY';
export const CRUD_OPTIONS_METADATA = 'NEST_CRUD_CRUD_OPTIONS_METADATA';
export const CRUD_AUTH_OPTIONS_METADATA = 'NEST_CRUD_CRUD_AUTH_OPTIONS_METADATA';
